/* eslint-disable */
module.exports = [
  {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
          },
          "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
          "id": "5a2EaR3hamoenG9rDuVn8j",
          "name": "Prince",
          "type": "artist",
          "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/7nXJ5k4XgRj5OLg9m8V3zc"
      },
      "href": "https://api.spotify.com/v1/albums/7nXJ5k4XgRj5OLg9m8V3zc",
      "id": "7nXJ5k4XgRj5OLg9m8V3zc",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/b06f26ee223372607bf0be8188cf94ffe0704bd6",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/8b171c29fa2d68816b23a9166b5354fbe0db3b1a",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/00f45f84cc30a651bd9575c9663465996780c9cd",
          "width": 64
        }
      ],
      "name": "Purple Rain",
      "release_date": "1984-06-25",
      "release_date_precision": "day",
      "total_tracks": 9,
      "type": "album",
      "uri": "spotify:album:7nXJ5k4XgRj5OLg9m8V3zc"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
        },
        "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
        "id": "5a2EaR3hamoenG9rDuVn8j",
        "name": "Prince",
        "type": "artist",
        "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 520786,
    "explicit": false,
    "external_ids": {
      "isrc": "USWB10001880"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/54X78diSLoUDI3joC2bjMz"
    },
    "href": "https://api.spotify.com/v1/tracks/54X78diSLoUDI3joC2bjMz",
    "id": "54X78diSLoUDI3joC2bjMz",
    "is_local": false,
    "name": "Purple Rain",
    "popularity": 72,
    "preview_url": "https://p.scdn.co/mp3-preview/2fe008411edea4f21355301daa8993663eaf46f8?cid=774b29d4f13844c495f206cafdad9c86",
    "track_number": 9,
    "type": "track",
    "uri": "spotify:track:54X78diSLoUDI3joC2bjMz"
  },
  {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
          },
          "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
          "id": "5a2EaR3hamoenG9rDuVn8j",
          "name": "Prince",
          "type": "artist",
          "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/7nXJ5k4XgRj5OLg9m8V3zc"
      },
      "href": "https://api.spotify.com/v1/albums/7nXJ5k4XgRj5OLg9m8V3zc",
      "id": "7nXJ5k4XgRj5OLg9m8V3zc",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/b06f26ee223372607bf0be8188cf94ffe0704bd6",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/8b171c29fa2d68816b23a9166b5354fbe0db3b1a",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/00f45f84cc30a651bd9575c9663465996780c9cd",
          "width": 64
        }
      ],
      "name": "Purple Rain",
      "release_date": "1984-06-25",
      "release_date_precision": "day",
      "total_tracks": 9,
      "type": "album",
      "uri": "spotify:album:7nXJ5k4XgRj5OLg9m8V3zc"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
        },
        "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
        "id": "5a2EaR3hamoenG9rDuVn8j",
        "name": "Prince",
        "type": "artist",
        "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 352906,
    "explicit": false,
    "external_ids": {
      "isrc": "USWB10001877"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/51H2y6YrNNXcy3dfc3qSbA"
    },
    "href": "https://api.spotify.com/v1/tracks/51H2y6YrNNXcy3dfc3qSbA",
    "id": "51H2y6YrNNXcy3dfc3qSbA",
    "is_local": false,
    "name": "When Doves Cry",
    "popularity": 67,
    "preview_url": "https://p.scdn.co/mp3-preview/5fc1bc59898ea8d0d23cf88810828d014020ef5d?cid=774b29d4f13844c495f206cafdad9c86",
    "track_number": 6,
    "type": "track",
    "uri": "spotify:track:51H2y6YrNNXcy3dfc3qSbA"
  },
  {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
          },
          "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
          "id": "5a2EaR3hamoenG9rDuVn8j",
          "name": "Prince",
          "type": "artist",
          "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/7nXJ5k4XgRj5OLg9m8V3zc"
      },
      "href": "https://api.spotify.com/v1/albums/7nXJ5k4XgRj5OLg9m8V3zc",
      "id": "7nXJ5k4XgRj5OLg9m8V3zc",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/b06f26ee223372607bf0be8188cf94ffe0704bd6",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/8b171c29fa2d68816b23a9166b5354fbe0db3b1a",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/00f45f84cc30a651bd9575c9663465996780c9cd",
          "width": 64
        }
      ],
      "name": "Purple Rain",
      "release_date": "1984-06-25",
      "release_date_precision": "day",
      "total_tracks": 9,
      "type": "album",
      "uri": "spotify:album:7nXJ5k4XgRj5OLg9m8V3zc"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
        },
        "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
        "id": "5a2EaR3hamoenG9rDuVn8j",
        "name": "Prince",
        "type": "artist",
        "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 280000,
    "explicit": true,
    "external_ids": {
      "isrc": "USWB19903188"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/0QeI79sp1vS8L3JgpEO7mD"
    },
    "href": "https://api.spotify.com/v1/tracks/0QeI79sp1vS8L3JgpEO7mD",
    "id": "0QeI79sp1vS8L3JgpEO7mD",
    "is_local": false,
    "name": "Let's Go Crazy",
    "popularity": 58,
    "preview_url": "https://p.scdn.co/mp3-preview/85dd430202f409d4e960e9169cfdddd38fe46ade?cid=774b29d4f13844c495f206cafdad9c86",
    "track_number": 1,
    "type": "track",
    "uri": "spotify:track:0QeI79sp1vS8L3JgpEO7mD"
  },
  {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
          },
          "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
          "id": "5a2EaR3hamoenG9rDuVn8j",
          "name": "Prince",
          "type": "artist",
          "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/7nXJ5k4XgRj5OLg9m8V3zc"
      },
      "href": "https://api.spotify.com/v1/albums/7nXJ5k4XgRj5OLg9m8V3zc",
      "id": "7nXJ5k4XgRj5OLg9m8V3zc",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/b06f26ee223372607bf0be8188cf94ffe0704bd6",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/8b171c29fa2d68816b23a9166b5354fbe0db3b1a",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/00f45f84cc30a651bd9575c9663465996780c9cd",
          "width": 64
        }
      ],
      "name": "Purple Rain",
      "release_date": "1984-06-25",
      "release_date_precision": "day",
      "total_tracks": 9,
      "type": "album",
      "uri": "spotify:album:7nXJ5k4XgRj5OLg9m8V3zc"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
        },
        "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
        "id": "5a2EaR3hamoenG9rDuVn8j",
        "name": "Prince",
        "type": "artist",
        "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 178986,
    "explicit": false,
    "external_ids": {
      "isrc": "USWB10001878"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/6fBwVe6udYdnRqwqo06if8"
    },
    "href": "https://api.spotify.com/v1/tracks/6fBwVe6udYdnRqwqo06if8",
    "id": "6fBwVe6udYdnRqwqo06if8",
    "is_local": false,
    "name": "I Would Die 4 U",
    "popularity": 57,
    "preview_url": "https://p.scdn.co/mp3-preview/395d416c1d2bc452c4326513cc2ca46f572cb836?cid=774b29d4f13844c495f206cafdad9c86",
    "track_number": 7,
    "type": "track",
    "uri": "spotify:track:6fBwVe6udYdnRqwqo06if8"
  },
  {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
          },
          "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
          "id": "5a2EaR3hamoenG9rDuVn8j",
          "name": "Prince",
          "type": "artist",
          "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/12DmuRtZNTx84ELHKD3VGL"
      },
      "href": "https://api.spotify.com/v1/albums/12DmuRtZNTx84ELHKD3VGL",
      "id": "12DmuRtZNTx84ELHKD3VGL",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/a4d8d1f8d0673a46ac6787e3924b08600c8d4f2f",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ac728db5225a82a0257edae901490ab3c222d6e3",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/901a21198f678858da3ab1354450b94a7800287e",
          "width": 64
        }
      ],
      "name": "Purple Rain Deluxe (Expanded Edition)",
      "release_date": "2017-06-23",
      "release_date_precision": "day",
      "total_tracks": 35,
      "type": "album",
      "uri": "spotify:album:12DmuRtZNTx84ELHKD3VGL"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j"
        },
        "href": "https://api.spotify.com/v1/artists/5a2EaR3hamoenG9rDuVn8j",
        "id": "5a2EaR3hamoenG9rDuVn8j",
        "name": "Prince",
        "type": "artist",
        "uri": "spotify:artist:5a2EaR3hamoenG9rDuVn8j"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 178266,
    "explicit": false,
    "external_ids": {
      "isrc": "USWB11700641"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/4hvxrI9P7c480gW0arZn3d"
    },
    "href": "https://api.spotify.com/v1/tracks/4hvxrI9P7c480gW0arZn3d",
    "id": "4hvxrI9P7c480gW0arZn3d",
    "is_local": false,
    "name": "I Would Die 4 U - 7\" Single Edit; 2017 Remaster",
    "popularity": 52,
    "preview_url": "https://p.scdn.co/mp3-preview/69800c02456490eeafc99a80f9cfa5928b33060d?cid=774b29d4f13844c495f206cafdad9c86",
    "track_number": 32,
    "type": "track",
    "uri": "spotify:track:4hvxrI9P7c480gW0arZn3d"
  }
]